# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_processing.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16video_processing.proto\x12\x10video_processing\"\xa9\x01\n\nVideoFrame\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nframe_data\x18\x02 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x12\x31\n\x08metadata\x18\x07 \x01(\x0b\x32\x1f.video_processing.FrameMetadata\"\xa0\x01\n\rFrameMetadata\x12\x15\n\rcamera_facing\x18\x01 \x01(\t\x12\x0f\n\x07quality\x18\x02 \x01(\x02\x12\x39\n\x05\x65xtra\x18\x03 \x03(\x0b\x32*.video_processing.FrameMetadata.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa7\x01\n\x13HealthCheckResponse\x12\x43\n\x06status\x18\x01 \x01(\x0e\x32\x33.video_processing.HealthCheckResponse.ServingStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\xca\x01\n\x16VideoProcessingService\x12T\n\x12ProcessVideoStream\x12\x1c.video_processing.VideoFrame\x1a\x1c.video_processing.VideoFrame(\x01\x30\x01\x12Z\n\x0bHealthCheck\x12$.video_processing.HealthCheckRequest\x1a%.video_processing.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_processing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAMEMETADATA_EXTRAENTRY']._options = None
  _globals['_FRAMEMETADATA_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_VIDEOFRAME']._serialized_start=45
  _globals['_VIDEOFRAME']._serialized_end=214
  _globals['_FRAMEMETADATA']._serialized_start=217
  _globals['_FRAMEMETADATA']._serialized_end=377
  _globals['_FRAMEMETADATA_EXTRAENTRY']._serialized_start=333
  _globals['_FRAMEMETADATA_EXTRAENTRY']._serialized_end=377
  _globals['_HEALTHCHECKREQUEST']._serialized_start=379
  _globals['_HEALTHCHECKREQUEST']._serialized_end=416
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=419
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=586
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=528
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=586
  _globals['_VIDEOPROCESSINGSERVICE']._serialized_start=589
  _globals['_VIDEOPROCESSINGSERVICE']._serialized_end=791
# @@protoc_insertion_point(module_scope)
