# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_processing_pb2 as video__processing__pb2


class VideoProcessingServiceStub(object):
    """Service definition for video processing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVideoStream = channel.stream_stream(
                '/video_processing.VideoProcessingService/ProcessVideoStream',
                request_serializer=video__processing__pb2.VideoFrame.SerializeToString,
                response_deserializer=video__processing__pb2.VideoFrame.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/video_processing.VideoProcessingService/HealthCheck',
                request_serializer=video__processing__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=video__processing__pb2.HealthCheckResponse.FromString,
                )


class VideoProcessingServiceServicer(object):
    """Service definition for video processing
    """

    def ProcessVideoStream(self, request_iterator, context):
        """Bidirectional streaming for real-time video processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVideoStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessVideoStream,
                    request_deserializer=video__processing__pb2.VideoFrame.FromString,
                    response_serializer=video__processing__pb2.VideoFrame.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=video__processing__pb2.HealthCheckRequest.FromString,
                    response_serializer=video__processing__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_processing.VideoProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoProcessingService(object):
    """Service definition for video processing
    """

    @staticmethod
    def ProcessVideoStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/video_processing.VideoProcessingService/ProcessVideoStream',
            video__processing__pb2.VideoFrame.SerializeToString,
            video__processing__pb2.VideoFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/video_processing.VideoProcessingService/HealthCheck',
            video__processing__pb2.HealthCheckRequest.SerializeToString,
            video__processing__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
